// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYn_r3wBs2nqpcZzgVMMXhmqaqyWkhK7w',
    appId: '1:221311295793:web:e5d83df709b6bc3b8a9010',
    messagingSenderId: '221311295793',
    projectId: 'management-ing',
    authDomain: 'management-ing.firebaseapp.com',
    storageBucket: 'management-ing.appspot.com',
    measurementId: 'G-509ZTTS7R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqLN40wPzd8sj6iPJLKXQJllvrhw7w70c',
    appId: '1:221311295793:android:62cfbe13c39d6b508a9010',
    messagingSenderId: '221311295793',
    projectId: 'management-ing',
    storageBucket: 'management-ing.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaIHm5GALWcxCvAZvonuS29stWK8N1k5o',
    appId: '1:221311295793:ios:9ca72e83be4d20b08a9010',
    messagingSenderId: '221311295793',
    projectId: 'management-ing',
    storageBucket: 'management-ing.appspot.com',
    iosBundleId: 'com.example.schoolManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaIHm5GALWcxCvAZvonuS29stWK8N1k5o',
    appId: '1:221311295793:ios:9ca72e83be4d20b08a9010',
    messagingSenderId: '221311295793',
    projectId: 'management-ing',
    storageBucket: 'management-ing.appspot.com',
    iosBundleId: 'com.example.schoolManagementSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYn_r3wBs2nqpcZzgVMMXhmqaqyWkhK7w',
    appId: '1:221311295793:web:08d02df5e719604b8a9010',
    messagingSenderId: '221311295793',
    projectId: 'management-ing',
    authDomain: 'management-ing.firebaseapp.com',
    storageBucket: 'management-ing.appspot.com',
    measurementId: 'G-71LY0Q23DD',
  );

}